### PR TITLE
GP-1968: Add validations to 'Birth date' and 'Year of Birth' fields

### PR DESCRIPTION
**Pull request by awg-github**

### CODE REVIEW

**Review by pfigel — CHANGES_REQUESTED** [review]
One scenario is not working: When updating the date of birth in the "Demographics" block to a value that's *not* in the current year (i.e. `01/01/2018`), the value is not stored at all. Interestingly, it works  with any date in 2019.

**Comment by awg-github** [comment]
I can't reproduce it. Please describe in more detail.

**Comment by pfigel** [comment]
Steps to reproduce are:
- Open an existing contact
- Enter Date of Birth "1991-02-10" in the "Demographics" block and save
- Year of Birth is set to "1991"
- Date of birth **is empty**

(If you try this with "2019-02-10" or any other date in the current year, it works as expected.)

Tested with b2ede1b0d137f817b0ffe0319dd829db863987e1 on Civi 5.19.4.

**Comment by pfigel** [comment]
LGTM, thanks @awg-github!

**Pull request merged**
