### PR TITLE
GP-44377: Add custom civioffice form with ckeditor.

### PR DESCRIPTION
**Pull request by awg-github**

### CODE REVIEW

**Comment by jensschuppe** [comment]
Would this be worth a PR to [systopia/de.systopia.civioffice](https://github.com/systopia/de.systopia.civioffice)?

**Comment by pfigel** [comment]
@jensschuppe yes, probably a good addition! We're planning to add a few more quite Greenpeace-specific things to this form (and haven't tested the existing code yet), but the WYSIWYG-thing can probably be contributed upstream.

The only tricky part is that the "Use PHPWord macros for token replacement" setting may vary if you have multiple document renderers, so we'd either need to switch between WYSIWYG and native textareas depending on the selected renderer, or just document the fact and gracefully remove any HTML added by the editor (might be a bit tricky).

(We were able to just ignore this issue since we only have one renderer where the setting is always enabled.)

**Comment by jensschuppe** [comment]
> The only tricky part is that the "Use PHPWord macros for token replacement" setting may vary if you have multiple document renderers, so we'd either need to switch between WYSIWYG and native textareas depending on the selected renderer, or just document the fact and gracefully remove any HTML added by the editor (might be a bit tricky).

… because only with this setting tokens are replaced with HTML-formatted token messages …? I'd say we should rather deprecate the regex replacement of tokens in favor of the PhpWord template processor and macros.

**Comment by pfigel** [comment]
> I'd say we should rather deprecate the regex replacement of tokens in favor of the PhpWord template processor and macros.

That sounds like the better option indeed.

I think the only real blocker for that (and for replacing everything with WYSIWYG) would be this issue: https://github.com/systopia/de.systopia.civioffice/issues/30
Currently, you'd have to be very careful with how you use formatting, or you'd end up replacing the entire paragraph that contains the token. We can work around this for now, but it's probably going to be a bit confusing for users.

It looks like there's been some prior work on fixing this in a PR. We can provide some funding if you/SYSTOPIA are interested in working on a fix for this?

**Comment by jensschuppe** [comment]
Thanks for the funding offer, I'll pass that on to @bjendres, @peth-systopia, @fabian-systopia - not sure why that approach in systopia/de.systopia.civioffice#30 has net been pursued any further.

**Pull request merged**
